import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "black",
  },
  Text2: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "black",
  },
  TextInput: {
    borderWidth: 3,
    backgroundColor: "white",
    borderColor: "gray",
    padding: 10,
    marginTop: 10,
    borderRadius: 10,
  },
  imgLogo: {
    height: 250,
    width: 250,
    resizeMode: "cover",
    marginTop: 30,
  },
  titulo: {
    color: "white",
    fontSize: 30,
    fontWeight: "bold",
    marginTop: 35,
  },
  TextAlcool: {
    color: "white",
    marginTop: 20,
    fontSize: 15,
    fontWeight: "bold",
  },
  TextGasolina: {
    color: "white",
    marginTop: 20,
    fontSize: 15,
    fontWeight: "bold",
  },
  Touchable: {
    borderWidth: 3,
    backgroundColor: "red",
    padding: 10,
    marginTop: 10,
    textShadowColor: "red",
    width: 215,
    borderRadius: 10,
  },
  textButton: {
    color: "white",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 15,
    borderRadius: 10,
  },
  Text: {
    fontSize: 20,
    color: "white",
    marginTop: 25,
  },
  TouchableModal: {
    borderWidth: 3,
    backgroundColor: "black",
    padding: 10,
    marginTop: 10,
    textShadowColor: "red",
    width: "10%",
    height: "5%",
    borderColor: "red",
    borderRadius: 10,
  },
  textModal: {
    color: "red",
    textAlign: "center",
    fontWeight: "bold",
  },
  compensa: {
    color: "green",
    fontWeight: "bold",
    fontSize: 30,
    marginTop: 25,
  },
  Preços: {
    color: "white",
    fontWeight: "bold",
    fontSize: 30,
    marginTop: 25,
  },
});
